`timescale 1ns / 1ps

module tb_lzrw1_decompressor();

    reg clk;
    reg rst;
    reg start;
    reg [7:0] data_in;
    reg data_in_valid;
    reg eof;

    wire [7:0] data_out;
    wire out_valid;
    wire done;

    integer in_file_id, out_file_id, char_in;

    // Instantiate UUT
    lzrw1_decompressor uut (
        .clk(clk),
        .rst(rst),
        .start(start),
        .data_in(data_in),
        .data_in_valid(data_in_valid),
        .eof(eof),
        .data_out(data_out),
        .out_valid(out_valid),
        .done(done)
    );

    // 100MHz clock
    always #5 clk = ~clk;

    initial begin
        clk = 0; rst = 1; start = 0; 
        data_in = 0; data_in_valid = 0; eof = 0;

        // Read the binary file generated by our compressor testbench!
        in_file_id = $fopen("compressed_out.bin", "rb");
        out_file_id = $fopen("decompressed_out.txt", "w"); 

        if (in_file_id == 0 || out_file_id == 0) begin
            $display("ERROR: File I/O failure. Ensure compressed_out.bin exists.");
            $finish;
        end

        #20 rst = 0; 
        #10 start = 1;
        #10 start = 0;

        $display("Starting decompression...");

        // Load the entire compressed file into the hardware
        while (!$feof(in_file_id)) begin
            char_in = $fgetc(in_file_id);
            if (char_in != -1) begin
                data_in = char_in[7:0]; 
                data_in_valid = 1;
                #10; 
            end
        end
        
        data_in_valid = 0;
        eof = 1; // Trigger the hardware to start decoding
        #10 eof = 0;

        // Wait until the hardware says it is completely done
        wait (done == 1'b1);
        
        #50;
        $fclose(in_file_id);
        $fclose(out_file_id);
        
        $display("Done! Successfully reversed compression.");
        $display("Check 'decompressed_out.txt' to verify it matches 'input.txt'!");
        $finish;
    end

    // Monitor Output: Write the decompressed bytes directly to the new file
    always @(posedge clk) begin
        if (out_valid) begin
            $fwrite(out_file_id, "%c", data_out);
        end
    end
endmodule
